# Generated by Django 4.1.7 on 2023-02-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0002_sleepandmood_delete_sleep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='SleepAndMood',
        ),
    ]
